# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: street_address 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "street_address".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andrew Stevens".freeze]
  s.date = "2021-04-15"
  s.description = "A Ruby port of the Geo::StreetAddress::US Library, originally by Jeremy Hubert".freeze
  s.email = "astevens@tstmedia.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/street_address.rb",
    "street_address.gemspec",
    "test/helper.rb",
    "test/test_street_address.rb"
  ]
  s.homepage = "http://github.com/astevens/street_address".freeze
  s.rubygems_version = "3.0.3".freeze
  s.summary = "US Street address parser".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<street_address>.freeze, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>.freeze, [">= 0"])
    else
      s.add_dependency(%q<street_address>.freeze, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<street_address>.freeze, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>.freeze, [">= 0"])
  end
end

